apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: rook-prometheus
  namespace: rook
spec:
  serviceMonitorSelector:
    matchLabels:
      team: rook
  resources:
    requests:
      memory: 400Mi