apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-share"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi