---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ .Release.Namespace }}
spec:
  monitoring:
    rulesNamespace: {{ default .Release.Namespace .Values.monitoring.rulesNamespaceOverride }}
{{ toYaml .Values.monitoring | indent 4 }}

{{ toYaml .Values.cephClusterSpec | indent 2 }}
