kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: csi-rbdplugin-attacher
  namespace: {{ .Namespace }}  
spec:
  serviceName: csi-rbdplugin-attacher
  replicas: 1
  selector:
    matchLabels:
      app: csi-rbdplugin-attacher  
  template:
    metadata:
      labels:
        app: csi-rbdplugin-attacher
    spec:
      serviceAccount: rook-csi-rbd-attacher-sa
      containers:
        - name: csi-rbdplugin-attacher
          image: {{ .AttacherImage }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: unix://csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/rbd.csi.ceph.com
            type: DirectoryOrCreate
