apiVersion: v1
kind: Pod
metadata:
  name: rook-client
spec:
  containers:
  - name: rook-client
    image: quay.io/rook/k8s-demo
    imagePullPolicy: IfNotPresent
    command: ["sleep", "36500d"]
    securityContext:
      privileged: true
    env:
      - name: ROOK_API_SERVER_ENDPOINT
        value: rookd-api:8124
    volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: libmodules
  volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: libmodules
        hostPath:
          path: /lib/modules