apiVersion: rook.io/v1alpha1
kind: ObjectStore
metadata:
  name: my-store
  namespace: rook
spec:
  # The pool spec used to create the metadata pools
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  # The pool spec used to create the data pool
  dataPool:
    failureDomain: osd
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  # The gaeteway service configuration
  gateway:
    # type of the gateway (s3)
    type: s3
    # A reference to the secret in the rook namespace where the ssl certificate is stored
    sslCertificateRef: 
    # The port that RGW pods will listen on
    port: 53390
    # The number of pods in the replicaset
    replicas: 1
    # The affinity rules for the rgw pods
    placement:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: role
    #          operator: In
    #          values:
    #          - rgw-node
    #  tolerations:
    #  - key: rgw-node
    #    operator: Exists
  # The zone information for replication across clusters (not implemented)
  #zone:
  #  realm: myrealm
  #  group: mygroup
  #  master:
  #    url: https://my-master-zone-gateway/
  #    accessKey: my-master-zone-access-key
  #    secret: my-master-zone-secret