name: Mod check
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  modcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: run mod check
      run: GOPATH=$(go env GOPATH) make -j $(nproc) mod.check

    - name: validate modcheck
      run: tests/scripts/validate_modified_files.sh modcheck
